githubConfigUrl: ${github_config_url}

githubConfigSecret:
  github_token: ${github_pat}

containerMode:
  type: kubernetes-novolume

controllerServiceAccount:
  namespace: ${k8s_namespace}
  name: arc-runner-set-controller